services:
  pec_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pec_crawler
    env_file: .env
    environment:
      TZ: ${TZ}
      RUN_AT: ${RUN_AT}
      # Monta a URL a partir das variáveis do .env
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s